import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import { sveltePreprocess } from "svelte-preprocess";
import process from "process";
import { builtinModules } from "node:module";

// EventEmitter shim plugin for mobile WebView compatibility
const EventEmitterShimPlugin = {
	name: "event-emitter-shim",
	setup(build) {
		build.onResolve({ filter: /^events$/ }, (args) => {
			return { path: args.path, namespace: "event-emitter-shim" };
		});

		build.onLoad(
			{ filter: /^events$/, namespace: "event-emitter-shim" },
			() => {
				return {
					contents: `
					class EventEmitter {
						constructor() {
							this.events = new Map();
						}
						on(event, listener) {
							if (!this.events.has(event)) {
								this.events.set(event, []);
							}
							this.events.get(event).push(listener);
							return this;
						}
						emit(event, ...args) {
							if (this.events.has(event)) {
								this.events.get(event).forEach(listener => listener(...args));
							}
							return this;
						}
						off(event, listener) {
							if (this.events.has(event)) {
								const listeners = this.events.get(event);
								const index = listeners.indexOf(listener);
								if (index > -1) {
									listeners.splice(index, 1);
								}
							}
							return this;
						}
					}
					export { EventEmitter };
				`,
					loader: "js",
				};
			},
		);
	},
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [
		EventEmitterShimPlugin,
		esbuildSvelte({
			compilerOptions: { css: "injected" },
			preprocess: sveltePreprocess(),
		}),
	],
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
